/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Piplup.glb -o src/components/Piplup.jsx 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Piplup({ hovered, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Piplup.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log("企鹅", actions);
    const anim = hovered ? "waving" : null;
    if (actions[anim]) actions[anim].reset().fadeIn(0.5).play();
    return () => (actions[anim] ? actions[anim].fadeOut(0.5) : null);
  }, [hovered]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Piplup">
          <primitive object={nodes.TopN} />
          <skinnedMesh
            name="Piplup002"
            geometry={nodes.Piplup002.geometry}
            material={materials["142.002"]}
            skeleton={nodes.Piplup002.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Piplup.glb");
